@Echo OFF
REM Generated by Omertron's YAMJ GUI Config v1.0
REM Created on 2013-02-21 13:14:09
REM http://MediaPlayerSite.com/YAMJ_GUI_Config

C:
CD \YAMJ

CALL MovieJukebox My_Library.xml -o D:\VideoPath

pause
exit
